spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/fintech
    driver-class-name: org.h2.Driver
    username: sa
    password: 123
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true