spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/fintech
    driver-class-name: org.h2.Driver
    username: sa
    password: 123
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
          format_sql: true
          default_schema: public # 또는 원하는 스키마 이름
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework: DEBUG
    org.hibernate: ERROR